name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libnghttp2-dev libbrotli-dev zlib1g-dev \
          python3 python3-pip ninja-build gyp pkg-config
        sudo pip3 install gyp-next

    - name: Build curl-impersonate
      run: |
        ./scripts/build-deps.sh

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Package binary
      run: |
        npm run package
        ls -la build/stage || true
        find . -name "*.tar.gz" || true

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/**/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}