name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        browser:
          - chrome
          - ff
        node-version:
          - 18
          - 20
        os:
          - ubuntu-20.04
          #- macOS-14

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - if: runner.os == 'Linux'
      name: Install Linux system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libnghttp2-dev libbrotli-dev zlib1g-dev \
          python3 python3-pip ninja-build gyp pkg-config
        sudo pip3 install gyp-next
        sudo ln -s /usr/bin/python3 /usr/bin/python || true

    - if: runner.os == 'macOS'
      name: Install macOS system dependencies
      run: brew install coreutils wget automake libtool cmake gnu-sed m4 autoconf groff

    - name: Build curl-impersonate
      run: |
        ./scripts/build-deps.sh

    - name: Install dependencies
      run: npm_config_browser=${{ matrix.browser }} npm ci

    - name: Build TypeScript
      run: npm run build

    - name: Build Binary
      run: |
        export npm_config_browser=${{ matrix.browser }}
        npm run build:binary
        # Rename the file to include the browser
        cd build/stage/releases/download/v*
        for f in *.tar.gz; do
          mv "$f" "${f/\{browser\}/${{ matrix.browser }}}"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries-${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.browser }}
        path: build/stage/**/*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Prepare artifacts for release
      run: |
        mkdir -p release
        find artifacts -type f -name "*.tar.gz" -exec cp {} release/ \;
        ls -la release/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*.tar.gz
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}